export const SET_ALGORITHM = 'SET_ALGORITHM';
export const GENERATE_LIST = 'GENERATE_LIST';
export const SET_INTERVAL = 'SET_INTERVAL';

export const SWAP_ELEMENTS = 'SWAP_ELEMENTS';
export const HIGHLIGH_ELEMENTS = 'HIGHLIGHT_ELEMENTS';

export const SET_VISUALISING = 'SET_VISUALISING';
