export const SET_ALGORITHM = 'SET_ALGORITHM';
export const GENERATE_LIST = 'GENERATE_LIST';
export const SET_SPEED = 'SET_SPEED';

export const SWAP_ELEMENTS = 'SWAP_ELEMENTS';
export const HIGHLIGHT_ELEMENTS = 'HIGHLIGHT_ELEMENTS';
export const ANIMATE_ELEMENTS = 'ANIMATE_ELEMENTS';

export const START_VISUALISATION = 'START_VISUALISATION';
export const STOP_VISUALISATION = 'STOP_VISUALISATION';
