export const SET_ALGORITHM = 'SET_ALGORITHM';
export const GENERATE_LIST = 'GENERATE_LIST';
export const SET_SPEED = 'SET_SPEED';

export const ANIMATE_ELEMENTS = 'ANIMATE_ELEMENTS';

export const START_VISUALISATION = 'START_VISUALISATION';
export const STOP_VISUALISATION = 'STOP_VISUALISATION';

export const REVERSE_LIST = 'REVERSE_LIST';
